import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {socket,joinWhatsAppSession} from './socket';
import {api,setToken,getToken,SESSION_ID} from './api';
import type {Chat,Message,ConnectionStatus} from './types';
import {Activity,Archive,AtSign,BarChart3,Bell,BookOpen,Check,ChevronDown,CircleUserRound,Code2,Copy,Database,Download,FileText,FolderOpen,Globe2,Group,Heart,Image as ImageIcon,Info,KeyRound,Link2,Loader2,LogOut,MapPin,Menu,MessageCircle,MoreVertical,Paperclip,Phone,Play,Plus,RefreshCw,Search,Send,Settings,Shield,Smile,SquarePen,Trash2,UserPlus,Users,Video,Volume2,Wifi, X} from 'lucide-react';
import './styles.css';

type ToolResult={ok:boolean;data?:any;error?:string};
const pretty=(x:any)=>JSON.stringify(x,null,2);
function App(){
 const [status,setStatus]=useState<ConnectionStatus>({connected:false,status:'closed',sessionId:SESSION_ID}); const [qr,setQr]=useState(''); const [chats,setChats]=useState<Chat[]>([]); const [selected,setSelected]=useState<Chat|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [query,setQuery]=useState(''); const [draft,setDraft]=useState(''); const [panel,setPanel]=useState<'chat'|'tools'>('chat'); const [tool,setTool]=useState('Session'); const [events,setEvents]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [toast,setToast]=useState(''); const [token,setTok]=useState(getToken()); const [mobileNav,setMobileNav]=useState(false);
 const visibleChats=useMemo(()=>chats.filter(c=>(c.name||c.pushName||c.jid).toLowerCase().includes(query.toLowerCase())),[chats,query]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const refresh=async()=>{try{const s=await api.status();setStatus(s); if(s.connected){const c=await api.chats();setChats(c?.chats||c||[])} }catch(e:any){notify(e.message)}};
 useEffect(()=>{
  const names=['whatsapp.connection','whatsapp.qr','whatsapp.messages.upsert','whatsapp.messages.update','whatsapp.chats.upsert','whatsapp.chats.update','whatsapp.contacts.upsert','whatsapp.groups.update','whatsapp.presence.update','whatsapp.history','whatsapp.event'];
  const onQr=(d:any)=>{if(d?.sessionId&&d.sessionId!==SESSION_ID)return;const value=d?.qr||d?.dataUrl||'';if(value){setQr(value);setStatus(v=>({...v,status:'qr',qr:value,qrAvailable:true}))}};
  const onConnection=(d:any)=>{if(d?.sessionId&&d.sessionId!==SESSION_ID)return;setStatus(v=>({...v,...d,connected:d?.status==='connected'||d?.connection==='open'}));if(d?.status==='connected'||d?.connection==='open')setQr('');if(d?.status==='logged_out'||d?.connection==='close')setQr('')};
  const onConnect=()=>joinWhatsAppSession();
  socket.on('connect',onConnect);
  names.forEach(n=>socket.on(n,(d:any)=>{setEvents(v=>[{name:n,data:d,at:new Date().toISOString()},...v].slice(0,200)); if(n==='whatsapp.qr')onQr(d); if(n==='whatsapp.connection')onConnection(d); if(n.includes('messages.upsert')){const arr=d?.messages||d; if(Array.isArray(arr))setMessages(v=>[...v,...arr])} if(n.includes('chats.upsert')){const arr=d?.chats||d; if(Array.isArray(arr))setChats(v=>{const m=new Map(v.map(x=>[x.jid,x]));arr.forEach((x:any)=>m.set(x.jid,{...m.get(x.jid),...x}));return [...m.values()]})}}));
  socket.connect();
  joinWhatsAppSession();
  refresh();
  const t=setInterval(refresh,3000);
  return()=>{clearInterval(t);socket.off('connect',onConnect);names.forEach(n=>socket.off(n))};
 },[]);
 const connect=async()=>{setBusy(true);try{setQr('');const r=await api.connect();setStatus(r);notify('Connection requested');}catch(e:any){notify(e.message)}finally{setBusy(false)}};
 const send=async()=>{if(!selected||!draft.trim())return;setBusy(true);try{const r=await api.text(selected.jid,draft.trim());setMessages(v=>[...v,(r?.message||{key:{id:r?.id,remoteJid:selected.jid,fromMe:true},message:{conversation:draft.trim()},messageTimestamp:Date.now()/1000})]);setDraft('')}catch(e:any){notify(e.message)}finally{setBusy(false)}};
 const choose=(c:Chat)=>{setSelected(c);setPanel('chat');setMessages([])};
 return <div className="app">
  <header className="topbar"><button className="iconbtn mobile" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button><div className="brand"><div className="logo"><MessageCircle size={19}/></div><div><b>Baileys</b><span>Control Center</span></div></div><div className="connection"><span className={'dot '+(status.connected?'on':'')}></span>{status.connected?'Connected':status.status==='qr'?'Scan QR':'Disconnected'}<button className="smallbtn" onClick={refresh}><RefreshCw size={14}/></button></div><div className="top-actions"><button className="iconbtn" title="Events" onClick={()=>{setPanel('tools');setTool('Live Events')}}><Activity size={18}/></button><button className="iconbtn" title="Settings" onClick={()=>{setPanel('tools');setTool('Session')}}><Settings size={18}/></button></div></header>
  <div className="layout">
   <aside className={'sidebar '+(mobileNav?'show':'')}>
    <div className="sidehead"><h2>Chats</h2><button className="round" onClick={connect}><SquarePen size={17}/></button></div>
    <div className="search"><Search size={16}/><input placeholder="Search chats" value={query} onChange={e=>setQuery(e.target.value)}/></div>
    <div className="filters"><button className="active">All</button><button>Unread</button><button>Groups</button></div>
    <div className="chatlist">{visibleChats.map((c:any)=><button className={'chatrow '+(selected?.jid===c.jid?'sel':'')} key={c.jid} onClick={()=>choose(c)}><Avatar name={c.name||c.pushName||c.jid}/><div className="chatmeta"><div className="chatline"><b>{c.name||c.pushName||c.jid}</b><span>{time(c.conversationTimestamp)}</span></div><div className="preview">{messagePreview(c.lastMessage)||c.jid}</div></div>{c.unreadCount?<span className="badge">{c.unreadCount}</span>:null}</button>)}{!visibleChats.length&&<div className="empty"><MessageCircle size={28}/><p>No chats loaded</p><small>Connect WhatsApp, then refresh.</small></div>}</div>
    <div className="sidebottom"><button onClick={()=>{setPanel('tools');setTool('Session')}}><KeyRound size={17}/> Session</button><button onClick={()=>{setPanel('tools');setTool('Groups')}}><Users size={17}/> Groups</button><button onClick={()=>{setPanel('tools');setTool('Privacy')}}><Shield size={17}/> Privacy</button><button onClick={()=>{setPanel('tools');setTool('Live Events')}}><Code2 size={17}/> Live events <span>{events.length}</span></button></div>
   </aside>
   <main className="main">{panel==='chat'?<ChatView selected={selected} messages={messages} draft={draft} setDraft={setDraft} send={send} busy={busy} onAction={async(a:string)=>{try{if(a==='read'&&selected)await api.chatRead({jid:selected.jid,read:true});if(a==='archive'&&selected)await api.archive({jid:selected.jid,archive:true});if(a==='mute'&&selected)await api.mute({jid:selected.jid,mute:true});if(a==='delete'&&selected)await api.chatDelete({jid:selected.jid});notify('Action completed');await refresh()}catch(e:any){notify(e.message)}}}/>:<Tools tool={tool} setTool={setTool} status={status} qr={qr} events={events} token={token} setToken={setTok} notify={notify} refresh={refresh} connect={connect}/>}</main>
   <aside className="rightpanel"><div className="righttitle">Test surface</div><div className="cap"><Wifi/><div><b>Realtime</b><p>Socket.IO event stream</p></div><span className="pill">{events.length}</span></div><div className="cap"><Database/><div><b>Persistence</b><p>Supabase-backed state</p></div><Check size={16}/></div><div className="cap"><FolderOpen/><div><b>Media</b><p>Upload/download pipeline</p></div></div><div className="rightsection"><b>Selected chat</b><pre>{selected?selected.jid:'None'}</pre></div><div className="rightsection"><b>Socket</b><p className="muted">{socket.connected?'Connected':'Connecting / offline'}</p></div></aside>
  </div>{toast&&<div className="toast">{toast}</div>}
 </div>
}
function Avatar({name}:{name:string}){return <div className="avatar">{name?.replace(/[^a-zA-Z0-9]/g,'').slice(0,2).toUpperCase()||'WA'}</div>}
function ChatView(p:any){const {selected,messages,draft,setDraft,send,busy,onAction}=p; if(!selected)return <div className="welcome"><div className="heroicon"><MessageCircle size={42}/></div><h1>WhatsApp test console</h1><p>Select a chat to exercise messaging, receipts, media and chat actions. Use the left tools for the complete API surface.</p><div className="welcomegrid"><Feature icon={<Send/>} title="Messages" text="Text, media, location, contacts and polls"/><Feature icon={<Users/>} title="Groups" text="Create, manage participants and metadata"/><Feature icon={<Shield/>} title="Privacy" text="Read and update WhatsApp privacy settings"/><Feature icon={<Activity/>} title="Events" text="Inspect every Socket.IO event in real time"/></div></div>;
 return <div className="chatview"><div className="chathead"><div className="user"><Avatar name={selected.name||selected.pushName||selected.jid}/><div><b>{selected.name||selected.pushName||selected.jid}</b><span>{selected.jid}</span></div></div><div className="headactions"><button className="iconbtn"><Phone size={18}/></button><button className="iconbtn"><Video size={18}/></button><button className="iconbtn" onClick={()=>onAction('mute')}><Volume2 size={18}/></button><button className="iconbtn" onClick={()=>onAction('archive')}><Archive size={18}/></button><button className="iconbtn" onClick={()=>onAction('delete')}><Trash2 size={18}/></button></div></div><div className="messages">{messages.length?messages.map((m:any,i:number)=><MessageBubble key={m.key?.id||i} m={m}/>):<div className="messageempty"><Info size={18}/> No messages loaded for this chat yet. History events will populate here.</div>}</div><div className="composer"><button className="iconbtn"><Paperclip size={19}/></button><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Type a message"/><button className="iconbtn"><Smile size={19}/></button><button className="send" onClick={send} disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<Send size={18}/>}</button></div></div>}
function MessageBubble({m}:any){const body=m.message?.conversation||m.message?.extendedTextMessage?.text||m.message?.imageMessage?.caption||m.message?.videoMessage?.caption||m.message?.documentMessage?.caption||m.message?.pollCreationMessageV3?.name||JSON.stringify(m.message); return <div className={'bubblewrap '+(m.key?.fromMe?'mine':'')}><div className="bubble">{body}<span>{time(m.messageTimestamp)}</span></div></div>}
function Feature({icon,title,text}:any){return <div className="feature"><div className="fi">{icon}</div><div><b>{title}</b><p>{text}</p></div></div>}
function Tools({tool,setTool,status,qr,events,token,setToken,notify,refresh,connect}:any){const tabs=['Session','Messages','Chat Actions','Groups','Privacy','Presence','History','Live Events','Raw API'];return <div className="tools"><div className="toolnav">{tabs.map(t=><button className={tool===t?'active':''} onClick={()=>setTool(t)} key={t}>{toolIcon(t)}{t}</button>)}</div><div className="toolbody">{tool==='Session'&&<Session status={status} qr={qr} token={token} setToken={setToken} notify={notify} refresh={refresh} connect={connect}/>} {tool==='Messages'&&<MessagesTool notify={notify}/>} {tool==='Chat Actions'&&<ChatTool notify={notify}/>} {tool==='Groups'&&<GroupsTool notify={notify}/>} {tool==='Privacy'&&<PrivacyTool notify={notify}/>} {tool==='Presence'&&<PresenceTool notify={notify}/>} {tool==='History'&&<HistoryTool notify={notify}/>} {tool==='Live Events'&&<Events events={events}/>} {tool==='Raw API'&&<RawApi notify={notify}/>}</div></div>}
function Section({title,desc,children}:any){return <section className="toolcard"><div className="sectitle"><div><h3>{title}</h3>{desc&&<p>{desc}</p>}</div></div>{children}</section>}
function Field({label,value,onChange,placeholder,type='text'}:any){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function ActionButton({children,onClick,secondary=false}:any){return <button className={'action '+(secondary?'secondary':'')} onClick={onClick}>{children}</button>}
function Session({status,qr,token,setToken,notify,refresh,connect}:any){return <div className="toolgrid"><Section title="Connection" desc="QR login and durable session management."><div className="statusbox"><span className={'dot '+(status.connected?'on':'')}></span><div><b>{status.status||status.connection||'closed'}</b><p>{status.connectedJid||status.user?.name||status.user?.id||'No linked account'}</p>{status.lastError&&<small className="muted">{status.lastError}</small>}</div></div><div className="row"><ActionButton onClick={connect}><Link2 size={16}/> Connect</ActionButton><ActionButton secondary onClick={refresh}><RefreshCw size={16}/> Refresh</ActionButton><ActionButton secondary onClick={async()=>{try{await api.logout();notify('Logged out');setTimeout(refresh,250)}catch(e:any){notify(e.message)}}}><LogOut size={16}/> Logout</ActionButton></div></Section><Section title="QR pairing" desc="Scan once; credentials remain in Supabase until logout."><div className="qrbox">{qr?<img alt="WhatsApp pairing QR code" src={qr.startsWith('data:')?qr:`data:image/png;base64,${qr}`} />:<div><KeyRound size={28}/><p>{status.status==='connecting'?'Waiting for WhatsApp QR…':'QR not available'}</p><small>Press Connect and wait for the QR event.</small></div>}</div>{status.qrAvailable&&<small className="muted">QR available for session {status.sessionId||SESSION_ID}</small>}</Section><Section title="API authentication" desc="Never put a Supabase service-role key in the browser."><Field label="Bearer token" value={token} onChange={(v:string)=>setToken(v)} placeholder="Supabase access token or gateway token"/><ActionButton onClick={()=>{setToken(token);notify('Token saved')}}><Check size={16}/> Save token</ActionButton></Section></div>}
function MessagesTool({notify}:any){const [jid,setJid]=useState('');const [text,setText]=useState('');const [kind,setKind]=useState('text');const [payload,setPayload]=useState('{}');const run=async()=>{try{let r:any;if(kind==='text')r=await api.text(jid,text);else {const parsed=JSON.parse(payload);const body={jid,...parsed,...(kind==='reaction'?{key:parsed.key,text:parsed.text}:{}),...(kind==='read'?{keys:parsed.keys}:{}),...(kind==='delete'?{key:parsed.key}:{}),...(kind==='edit'?{key:parsed.key,text:parsed.text}:{})};r=kind==='media'?await api.media(body):kind==='location'?await api.location(body):kind==='contact'?await api.contact(body):kind==='poll'?await api.poll(body):kind==='reaction'?await api.reaction(body):kind==='read'?await api.read(body):kind==='delete'?await api.del(body):await api.edit(body)}notify('Message request succeeded')}catch(e:any){notify(e.message)}};return <Section title="Message API" desc="Exercise all message routes from one place."><Field label="Target JID" value={jid} onChange={setJid} placeholder="919999999999@s.whatsapp.net"/><div className="seg">{['text','media','location','contact','poll','reaction','read','delete','edit'].map(k=><button className={kind===k?'active':''} onClick={()=>setKind(k)} key={k}>{k}</button>)}</div>{kind==='text'?<Field label="Text" value={text} onChange={setText} placeholder="Hello from the test console"/>:<label className="field"><span>JSON payload</span><textarea value={payload} onChange={e=>setPayload(e.target.value)}/></label>}<ActionButton onClick={run}><Play size={16}/> Run {kind}</ActionButton></Section>}
function ChatTool({notify}:any){const [jid,setJid]=useState('');const [kind,setKind]=useState('archive');const run=async()=>{try{const fn:any={archive:api.archive,mute:api.mute,read:api.chatRead,delete:api.chatDelete}[kind];await fn({jid,[kind==='read'?'read':kind]:kind==='read'?true:true});notify('Chat action succeeded')}catch(e:any){notify(e.message)}};return <Section title="Chat actions" desc="Archive, mute, mark read or delete a chat."><Field label="Chat JID" value={jid} onChange={setJid}/><div className="seg">{['archive','mute','read','delete'].map(k=><button className={kind===k?'active':''} onClick={()=>setKind(k)} key={k}>{k}</button>)}</div><ActionButton onClick={run}><Play size={16}/> Run</ActionButton></Section>}
function GroupsTool({notify}:any){const [jid,setJid]=useState('');const [payload,setPayload]=useState('{}');const run=async()=>{try{await api.group(jid);notify('Group loaded')}catch(e:any){notify(e.message)}};return <Section title="Groups" desc="Inspect a WhatsApp group and use the group API tabs elsewhere in the console."><Field label="Group JID" value={jid} onChange={setJid} placeholder="1203...@g.us"/><ActionButton onClick={run}><Play size={16}/> Load group</ActionButton><label className="field"><span>Payload</span><textarea value={payload} onChange={e=>setPayload(e.target.value)}/></label></Section>}
function PrivacyTool({notify}:any){const [data,setData]=useState<any>(null);const load=async()=>{try{setData(await api.privacy())}catch(e:any){notify(e.message)}};return <Section title="Privacy" desc="Read WhatsApp privacy settings."><ActionButton onClick={load}><RefreshCw size={16}/> Load</ActionButton>{data&&<pre className="json">{pretty(data)}</pre>}</Section>}
function PresenceTool({notify}:any){const [body,setBody]=useState('{"jid":"","type":"available"}');const run=async()=>{try{await api.presence(JSON.parse(body));notify('Presence updated')}catch(e:any){notify(e.message)}};return <Section title="Presence" desc="Send a presence update through the backend."><label className="field"><span>JSON payload</span><textarea value={body} onChange={e=>setBody(e.target.value)}/></label><ActionButton onClick={run}><Play size={16}/> Run</ActionButton></Section>}
function HistoryTool({notify}:any){return <Section title="History" desc="Inspect historical events emitted by the backend."><p className="muted">History events appear in Live Events as they arrive.</p></Section>}
function Events({events}:{events:any[]}){return <Section title="Live events" desc="Latest Socket.IO events received by this browser."><div className="events">{events.map((e:any,i:number)=><div className="event" key={i}><b>{e.name}</b><span>{e.at}</span><pre>{pretty(e.data)}</pre></div>)}</div></Section>}
function RawApi({notify}:any){const [path,setPath]=useState('/api/wa/status');const [method,setMethod]=useState('GET');const [body,setBody]=useState('{}');const [result,setResult]=useState('');const run=async()=>{try{const r=await fetch(`${apiBase()}${path.includes('?')?path:`${path}${path.includes('?')?'&':'?'}sessionId=${encodeURIComponent(SESSION_ID)}`}`,{method,headers:{'Content-Type':'application/json'},body:method==='GET'?undefined:body});setResult(await r.text())}catch(e:any){setResult(e.message)}};return <Section title="Raw API" desc="Call the gateway directly for debugging."><Field label="Path" value={path} onChange={setPath}/><div className="seg">{['GET','POST','PATCH','DELETE'].map(k=><button className={method===k?'active':''} onClick={()=>setMethod(k)} key={k}>{k}</button>)}</div><label className="field"><span>JSON body</span><textarea value={body} onChange={e=>setBody(e.target.value)}/></label><ActionButton onClick={run}><Play size={16}/> Run request</ActionButton>{result&&<pre className="json">{result}</pre>}</Section>}
function apiBase(){return import.meta.env.VITE_API_URL||'http://localhost:3000'}
function toolIcon(t:string){return <span className="ti">{t==='Session'?<KeyRound size={16}/>:t==='Messages'?<MessageCircle size={16}/>:t==='Chat Actions'?<Archive size={16}/>:t==='Groups'?<Users size={16}/>:t==='Privacy'?<Shield size={16}/>:t==='Presence'?<Wifi size={16}/>:t==='History'?<BookOpen size={16}/>:t==='Live Events'?<Activity size={16}/>:<Code2 size={16}/>}</span>}
function messagePreview(m:any){return m?.message?.conversation||m?.message?.extendedTextMessage?.text||m?.message?.imageMessage?.caption||m?.message?.videoMessage?.caption||''}
function time(v:any){if(!v)return '';const d=new Date(Number(v)<1e12?Number(v)*1000:Number(v));return d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
createRoot(document.getElementById('root')!).render(<App/>);
